#ifndef N2Z_LITE_KERNEL_H
#define N2Z_LITE_KERNEL_H
#define N2Z_LITE_KERNEL 1
#define COMPACT_LAYERS 23
#define COMPACT_HEAD_KERNEL 16
#define COMPACT_RECEPTIVE_FIELD 6347
#define COMPACT_WEIGHTS 1871
#endif
